[tool.poetry]
name = "Coriolis"
version = "2.5.0"
description = "Place and Route for semiconductors"
authors = ["Jean-Paul Chaput <Jean-Paul.Chaput@lip6.fr>"]
build = "build.py"
packages = [
  { include = "Coriolis"}
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ninja = ">=1.10"
cmake = ">=3"

[tool.poetry.scripts]

blif2vst = 'Coriolis:blif2vst'
cx2y = 'Coriolis:cx2y'
cyclop = 'Corilis:cyclop'
tutorial = 'Coriolis:tutorial'
unittests = 'Coriolis:unittests'
yosys_coriolis = 'Coriolis:yosys_coriolis'

[build-system]
requires = ["poetry-core", "setuptools", "cmake"]
build-backend = "poetry.core.masonry.api"

