[tool.poetry]
name = "coriolis"
version = "0.1.0"
description = "Place and Route for semiconductors"
authors = ["Your Name <you@example.com>"]
build = "build.py"


[tool.poetry.dependencies]
python = "^3.9"
PySide2 =  "^5.0"

[tool.poetry.dev-dependencies]
ninja = ">=1.10"
cmake = ">=3"

[build-system]
requires = ["poetry-core", "setuptools", "cmake"]
build-backend = "poetry.core.masonry.api"

