[tool.poetry]
name = "Coriolis"
version = "2.5.0"
description = "Place and Route for semiconductors"
authors = ["Jean-Paul Chaput <Jean-Paul.Chaput@lip6.fr>"]
build = "builder.py"
packages = [
  { include = "Coriolis"}
]

[tool.poetry.dependencies]
python = "^3.8"
find-libpython = "^0.3.0"

[tool.poetry.dev-dependencies]
cmake = ">=3"

[tool.poetry.scripts]
blif2vst =  'Coriolis:blif2vst'
cx2y = 'Coriolis:cx2y'
cyclop = 'Corilis:cyclop'
tutorial = 'Coriolis:tutorial'
unittests = 'Coriolis:unittests'
yosys_coriolis = 'Coriolis:yosys_coriolis'

[build-system]
requires = ["poetry-core", "setuptools", "cmake", "patchelf", "find-libpython"]
build-backend = "poetry.core.masonry.api"

[tool.cibuildwheel.linux]
skip = ["cp36-*", "cp37-*", "pp*"]
build-frontend = "build"
before-all = '''
 yum install -y \
 qt5-qtbase-devel qt5-qtsvg-devel \
 rapidjson-devel bison flex doxygen bzip2-devel flex-devel \
 boost-devel \
 boost-python boost-filesystem \
 boost-regex  boost-wave \
 python3-devel libxml2-devel \
 qwt-devel
'''
build-verbosity=2
