
name: Regression tests
on:   [workflow_dispatch]

jobs:
  Regression-Tests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
         path:       coriolis-2.x/src/coriolis
     - uses: actions/checkout@v3
       with:
         repository: lip6/alliance
         path:       coriolis-2.x/src/alliance
     - uses: actions/checkout@v3
       with:
         repository: lip6/alliance-check-toolkit
         path:       coriolis-2.x/src/alliance-check-toolkit
     - uses: actions/checkout@v3
       with:
         repository: YosysHQ/yosys
         path:       coriolis-2.x/src/yosys
         ref:        yosys-0.24
     - name: Update APT cache
       run: sudo apt-get update
     - name: Install software dependencies
       run: >
         sudo apt-get install libboost-all-dev rapidjson-dev \
                              python-dev-is-python3 \
                              qtbase5-dev qtbase5-dev-tools libqt5svg5-dev libqwt-qt5-dev \
                              libeigen3-dev liblemon-dev \
                              autotools-dev automake \
                              libxt-dev libxpm-dev libmotif-dev \
                              tcl-dev libffi-dev
     - name: ccache
       uses: hendrikmuhs/ccache-action@v1.2
     - name: Build Yosys
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         cd ${{ github.workspace }}/coriolis-2.x/src/yosys
         make ENABLE_PYOSYS=1 config-gcc
         make ENABLE_PYOSYS=1 PREFIX=/install PYTHON_DESTDIR=/install/lib64/python3.10/dist-packages DESTDIR=${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared install
     - name: Check for binaries
       run: ls ${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared/install/bin
     - name: Build Alliance
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         ${{ github.workspace }}/coriolis-2.x/src/coriolis/bootstrap/allianceInstaller.sh --github-runner=${{ github.workspace }}
     - name: Build Coriolis
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         ${{ github.workspace }}/coriolis-2.x/src/coriolis/bootstrap/ccb.py --root=${{ github.workspace }}/coriolis-2.x --project=coriolis --make="-j4 install"
